version: '3.8'

services:
  backend:
    build: ./restaurant_management_backend
    ports:
      - "5000:5000"
    env_file:
      - ./restaurant_management_backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./restaurant_management_admin
      args:
        - VITE_API_URL=http://localhost:5000/api
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
